name: load-data

on:
  push:
    branches: [main]

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{var.USER}}
      DB_PASSWORD: ${{secrets.PASS}}
      DB_HOST: ${{secrets.HOST}}
      DB_PORT: ${{secrets.PORT}}
      DB_NAME: ${{var.DB}}
      CSV_FILE: data/fda_adverse_events_2015_2026_CLEAN.csv
      DB_SCHEMA: staging
      DB_TABLE: adverse_events_raw


    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run flake8
        run: flake8 app.py

      - name: run mypy
        run: mypy app.py

      - name: run pylint
        run: pylint app.py

      - name: run script
        run: |
          python app.py